package com.guyde.nano.render;

import net.minecraft.client.model.ModelBase;
// Date: 4/10/2015 5:34:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;







public class ModelTarget extends ModelBase
{
  //fields
    ModelRenderer Leg_2;
    ModelRenderer Leg1;
    ModelRenderer Stand1;
    ModelRenderer Stand2;
    ModelRenderer Face;
  
  public ModelTarget()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Leg_2 = new ModelRenderer(this, 20, 22);
      Leg_2.addBox(0F, 0F, 0F, 2, 40, 2);
      Leg_2.setRotationPoint(-1.533333F, -14.26667F, 0F);
      Leg_2.setTextureSize(128, 64);
      Leg_2.mirror = true;
      setRotation(Leg_2, 0F, 0F, 0.2617994F);
      Leg1 = new ModelRenderer(this, 28, 22);
      Leg1.addBox(-1.933333F, 0F, 0F, 2, 40, 2);
      Leg1.setRotationPoint(1.466667F, -14.33333F, 0F);
      Leg1.setTextureSize(128, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, -0.2617994F);
      Stand1 = new ModelRenderer(this, 60, 52);
      Stand1.addBox(0F, 0F, 0F, 2, 2, 10);
      Stand1.setRotationPoint(6.266667F, 11F, -10F);
      Stand1.setTextureSize(128, 64);
      Stand1.mirror = true;
      setRotation(Stand1, 0F, 0F, -0.2617994F);
      Stand2 = new ModelRenderer(this, 36, 52);
      Stand2.addBox(0F, 0F, 0F, 2, 2, 10);
      Stand2.setRotationPoint(-8.333333F, 11F, -10F);
      Stand2.setTextureSize(128, 64);
      Stand2.mirror = true;
      setRotation(Stand2, 0F, 0F, 0.2617994F);
      Face = new ModelRenderer(this, 84, 42);
      Face.addBox(0F, 0F, 0F, 20, 20, 2);
      Face.setRotationPoint(-10F, -9F, -2F);
      Face.setTextureSize(128, 64);
      Face.mirror = true;
      setRotation(Face, -0.1858931F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Leg_2.render(f5);
    Leg1.render(f5);
    Stand1.render(f5);
    Stand2.render(f5);
    Face.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,null);
  }

}
